### ISSUE TITLE
Cannot build with gcc version 15.2.1

### ISSUE THREAD

**Issue by KirtusLeyba** [vlaci/openconnect-sso#202]
If I try to build with pipx as per the README, I get:

```
pip failed to build package:
    lxml

Some possibly relevant errors from pip install:
```
But it lists no errors.

If I try to build this way:
```
cd openconnect-sso
make dist
cd dist/
pipx install *.whl
```

```
Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    src/lxml/etree.c:155971:66: error: passing argument 1 of ‘__pyx_f_4lxml_5etree_11TreeBuilder__handleSaxData’ from incompatible pointer type [-Wincompatible-pointer-types]
    src/lxml/etree.c:156177:67: error: passing argument 1 of ‘__pyx_f_4lxml_5etree_11TreeBuilder__handleSaxStart’ from incompatible pointer type [-Wincompatible-pointer-types]
    src/lxml/etree.c:156330:65: error: passing argument 1 of ‘__pyx_f_4lxml_5etree_11TreeBuilder__handleSaxEnd’ from incompatible pointer type [-Wincompatible-pointer-types]
    src/lxml/etree.c:156576:64: error: passing argument 1 of ‘__pyx_f_4lxml_5etree_11TreeBuilder__handleSaxPi’ from incompatible pointer type [-Wincompatible-pointer-types]
    src/lxml/etree.c:156721:69: error: passing argument 1 of ‘__pyx_f_4lxml_5etree_11TreeBuilder__handleSaxComment’ from incompatible pointer type [-Wincompatible-pointer-types]
    src/lxml/etree.c:225370:73: error: passing argument 1 of ‘__pyx_f_4lxml_5etree_12_XSLTContext__copy’ from incompatible pointer type [-Wincompatible-pointer-types]
    src/lxml/etree.c:227187:71: error: passing argument 1 of ‘__pyx_f_4lxml_5etree_12_XSLTContext__copy’ from incompatible pointer type [-Wincompatible-pointer-types]
    error: command '/usr/bin/gcc' failed with exit code 1
    error: failed-wheel-build-for-install
```

I have seen this issue with -Wincompatible-pointer-types with other software when I use gcc 15.
